import React from 'react';
import { 
  FileDown, 
  FileText, 
  Table, 
  BarChart, 
  CheckCircle2,
  Clock,
  Download,
  Share2,
  ArrowUpRight
} from 'lucide-react';
import { motion } from 'motion/react';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';

const reportTypes = [
  { id: 'pembelajaran', label: 'Laporan Pembelajaran STEM', description: 'Detail aktivitas dan capaian belajar murid.', color: 'indigo' },
  { id: 'implementasi', label: 'Laporan Implementasi STEM', description: 'Monitoring progres di tingkat sekolah.', color: 'emerald' },
  { id: 'praktik_baik', label: 'Laporan Praktik Baik', description: 'Kumpulan dokumentasi keberhasilan.', color: 'blue' },
  { id: 'monitoring', label: 'Laporan Monitoring', description: 'Rekapitulasi pengawasan supervisi.', color: 'amber' },
  { id: 'evaluasi', label: 'Laporan Evaluasi', description: 'Statistik nilai dan rubrik penilaian.', color: 'rose' },
];

export default function Laporan() {
  const exportToExcel = (type: string) => {
    const ws = XLSX.utils.json_to_sheet([
      { Tanggal: '2026-08-12', Sekolah: 'SMPN 1 Solo', Proyek: 'Tempe STEM', Status: 'Selesai', Nilai: 85 },
      { Tanggal: '2026-08-11', Sekolah: 'SMAN 5 Bulukumba', Proyek: 'Pinisi Tech', Status: 'Berjalan', Nilai: 72 },
    ]);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Laporan");
    XLSX.writeFile(wb, `Laporan_${type}.xlsx`);
  };

  const exportToPDF = (type: string) => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text("LAPORAN STEM SINEMA", 20, 20);
    doc.setFontSize(12);
    doc.text(`Jenis Laporan: ${type}`, 20, 30);
    doc.text("Generated by AI STEM Platform", 20, 40);
    doc.save(`Laporan_${type}.pdf`);
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-extrabold text-slate-800">Pusat Laporan</h2>
          <p className="text-slate-500">Unduh data dan rekapitulasi dalam format PDF atau Excel.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reportTypes.map((report, i) => (
          <motion.div 
            key={report.id}
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: i * 0.05 }}
            className="bg-white rounded-3xl border border-slate-100 p-8 shadow-sm hover:shadow-xl transition-all group"
          >
            <div className={`w-14 h-14 rounded-2xl bg-${report.color}-50 text-${report.color}-600 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}>
              <FileText size={32} />
            </div>
            <h3 className="text-xl font-bold text-slate-800 mb-2">{report.label}</h3>
            <p className="text-sm text-slate-500 leading-relaxed mb-8">
              {report.description}
            </p>
            
            <div className="grid grid-cols-2 gap-3">
              <button 
                onClick={() => exportToPDF(report.id)}
                className="flex items-center justify-center gap-2 py-3 bg-slate-900 text-white rounded-xl text-xs font-bold hover:bg-slate-800 transition-all"
              >
                <FileDown size={14} />
                PDF
              </button>
              <button 
                onClick={() => exportToExcel(report.id)}
                className="flex items-center justify-center gap-2 py-3 border border-slate-200 text-slate-700 rounded-xl text-xs font-bold hover:bg-slate-50 transition-all"
              >
                <Table size={14} />
                Excel
              </button>
            </div>
          </motion.div>
        ))}
      </div>

      <div className="bg-indigo-50 rounded-3xl p-10 flex flex-col md:flex-row items-center gap-10 border border-indigo-100">
        <div className="flex-1 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-indigo-600 text-white rounded-full text-[10px] font-black tracking-widest uppercase">
            Fitur Pintar
          </div>
          <h3 className="text-3xl font-black text-indigo-900 leading-tight">Generate Laporan Otomatis dengan Narasi AI</h3>
          <p className="text-indigo-700 font-medium">
            Sistem kami dapat merangkum seluruh aktivitas menjadi narasi laporan yang profesional untuk dinas pendidikan.
          </p>
          <button className="flex items-center gap-2 text-indigo-600 font-black group">
            Pelajari Selengkapnya
            <ArrowUpRight size={20} className="group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform" />
          </button>
        </div>
        <div className="w-full max-w-[300px] bg-white p-6 rounded-2xl shadow-xl shadow-indigo-100 border border-indigo-50 space-y-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-bold text-slate-400">STATUS REKAP</span>
            <CheckCircle2 size={16} className="text-emerald-500" />
          </div>
          <div className="space-y-2">
            <div className="h-2 bg-slate-100 rounded-full w-full"></div>
            <div className="h-2 bg-slate-100 rounded-full w-4/5"></div>
            <div className="h-2 bg-slate-100 rounded-full w-2/3"></div>
          </div>
          <div className="pt-4 flex justify-between items-center text-xs">
            <span className="text-slate-500">Sinkronisasi:</span>
            <span className="font-bold text-indigo-600">Berhasil</span>
          </div>
        </div>
      </div>
    </div>
  );
}
